#include <doctest.h>

#include <cpp/Warning.hpp>

TEST_CASE("Warning.Clang")
{
    CPP_CLANG_SUPPRESS_WARNING_PUSH;
    CPP_CLANG_SUPPRESS_WARNING("-Wextra");
    CPP_CLANG_SUPPRESS_WARNING_POP;

    CPP_CLANG_SUPPRESS_WARNING_WITH_PUSH("-Wextra");
    CPP_CLANG_SUPPRESS_WARNING_POP;
}

TEST_CASE("Warning.GCC")
{
    CPP_GCC_SUPPRESS_WARNING_PUSH;
    CPP_GCC_SUPPRESS_WARNING("-Wextra");
    CPP_GCC_SUPPRESS_WARNING_POP;

    CPP_GCC_SUPPRESS_WARNING_WITH_PUSH("-Wextra");
    CPP_GCC_SUPPRESS_WARNING_POP;
}

TEST_CASE("Warning.MSVC")
{
    CPP_MSVC_SUPPRESS_WARNING_PUSH;
    CPP_MSVC_SUPPRESS_WARNING(4800);
    CPP_MSVC_SUPPRESS_WARNING_POP;

    CPP_MSVC_SUPPRESS_WARNING_WITH_PUSH(4800);
    CPP_MSVC_SUPPRESS_WARNING_POP;
}

TEST_CASE("Warning.CompilerWarning")
{
    CPP_COMPILER_WARNING("Test warning");
}
