name: CodeCoverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get-cmake
        uses: lukka/get-cmake@v3.17.2

      - name: Install tools
        run: |
          # Install lcov
          mkdir lcov
          wget --no-check-certificate -O - "https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-1.14.tar.gz" | tar --strip-components=1 -xz -C lcov
          cd lcov
          sudo make install

          echo "::set-env name=PATH::$(pwd)/lcov/bin:${PATH}"

          # Install g++
          sudo apt-get install g++-8

      - name: Build coverage data
        run: |
          # Create build directory
          mkdir build
          cd build

          # Build it
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="/usr/bin/g++-8" -DCMAKE_CXX_FLAGS="--coverage -g -O0" ..
          cmake --build . --clean-first

          # Generate coverage data
          ctest .

      - name: Process coverage data
        run: |
          lcov --directory build --capture --output-file coverage.info --gcov-tool gcov-8 # capture coverage info
          lcov --remove coverage.info "/usr/*" --output-file coverage.info # filter out system
          lcov --remove coverage.info "$(readlink -f test/include)/*" --output-file coverage.info # filter out doctest

          # List debug info
          lcov --list coverage.info # debug info

      - name: Upload coverage data
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.info
          flags: unittests
          name: ${{ runner.os }}.g++-8
          fail_ci_if_error: true